---
- name: Download JDK
  win_get_url:
    url: https://cfdownload.adobe.com/pub/adobe/coldfusion/java/java11/java11019/jdk-11.0.19_windows-x64_bin.zip
    dest: C:\Windows\Temp\jdk-11.0.19_windows-x64_bin.zip
    force: true
- name: Extract JDK
  win_shell: Expand-Archive -Path C:\Windows\Temp\jdk-11.0.19_windows-x64_bin.zip -DestinationPath C:\
- name: Set JAVA_HOME
  win_environment:
    name: JAVA_HOME
    value: C:\jdk-11.0.19
    level: machine
    state: present
