---
- name: Configure a log4j-logstash-56 machine image
  hosts: all
  vars:
    user_name: m0nk3y
    user_password: 7;@K"kPTM
  tasks:
    - import_tasks: tasks/windows_create_user.yml
      vars:
        username: "{{ user_name }}"
        password: "{{ user_password }}"
        user_groups: [Administrators, "Remote Desktop Users"]
    - import_tasks: tasks/windows_disable_automatic_updates.yml
    - import_tasks: tasks/windows_disable_windows_defender.yml
    - import_tasks: tasks/windows_disable_firewall.yml
    - import_tasks: tasks/windows_install_java.yml
    - import_tasks: tasks/windows_install_logstash.yml
      become: yes
      become_user: "{{ user_name }}"
      vars:
        ansible_become_method: runas
        ansible_become_password: "{{ user_password }}"
    - name: Change the hostname to log4j-logstash-56
      ansible.windows.win_hostname:
        name: log4j-logstash-56
      register: res
    - name: Reboot
      ansible.windows.win_reboot:
      when: res.reboot_required
    - name: Delete packer_user
      win_user:
        name: packer_user
        state: absent
