---
- name: Configure SNMP agent
  hosts: all
  remote_user: root
  vars:
    community_string: c0mmun1ty

  tasks:
    - name: Install SNMP
      ansible.builtin.apt:
        name:
          - snmp=5.7.3+dfsg-1.8ubuntu3
          - snmpd=5.7.3+dfsg-1.8ubuntu3
          - libsnmp30=5.7.3+dfsg-1.8ubuntu3
        update_cache: yes
    - name: Configure SNMP
      blockinfile:
        path: /etc/snmp/snmpd.conf
        backup: yes
        create: yes
        block: |
          master          agentx
          agentAddress udp:161,udp6:[::1]:161

          view   systemonly  included   .1.3.6.1.2.1.1
          view   systemonly  included   .1.3.6.1.2.1.25.1

          rocommunity public  default    -V systemonly
          rocommunity6 public  default   -V systemonly
          rwcommunity {{ community_string }}
    - name: Remove snmp.conf
      ansible.builtin.file:
        path: /etc/snmp/snmp.conf
        state: absent
    - name: Disable security updates
      ansible.builtin.apt:
        name: unattended-upgrades
        state: absent
